/*
 * Code for class WEL_COLOR_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1366_14326(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14327(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14328(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14329(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14330(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14331(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14332(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14333(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14334(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14335(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14336(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14337(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14338(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14339(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14340(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14341(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14342(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14343(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14344(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14345(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14346(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14347(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14348(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14349(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14350(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14351(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14352(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14353(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14354(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14355(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14356(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14357(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14358(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14359(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14360(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14361(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1366_14362(EIF_REFERENCE, EIF_TYPED_VALUE);
extern void EIF_Minit1366(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_COLOR_CONSTANTS}.color_scrollbar */
EIF_TYPED_VALUE F1366_14326 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_background */
EIF_TYPED_VALUE F1366_14327 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_desktop */
EIF_TYPED_VALUE F1366_14328 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_activecaption */
EIF_TYPED_VALUE F1366_14329 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_inactivecaption */
EIF_TYPED_VALUE F1366_14330 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_menu */
EIF_TYPED_VALUE F1366_14331 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_window */
EIF_TYPED_VALUE F1366_14332 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_windowframe */
EIF_TYPED_VALUE F1366_14333 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_menutext */
EIF_TYPED_VALUE F1366_14334 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_windowtext */
EIF_TYPED_VALUE F1366_14335 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_captiontext */
EIF_TYPED_VALUE F1366_14336 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_activeborder */
EIF_TYPED_VALUE F1366_14337 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_inactiveborder */
EIF_TYPED_VALUE F1366_14338 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_appworkspace */
EIF_TYPED_VALUE F1366_14339 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_highlight */
EIF_TYPED_VALUE F1366_14340 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_highlighttext */
EIF_TYPED_VALUE F1366_14341 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_3dface */
EIF_TYPED_VALUE F1366_14342 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_btnface */
EIF_TYPED_VALUE F1366_14343 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_3dshadow */
EIF_TYPED_VALUE F1366_14344 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_btnshadow */
EIF_TYPED_VALUE F1366_14345 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_graytext */
EIF_TYPED_VALUE F1366_14346 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_btntext */
EIF_TYPED_VALUE F1366_14347 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_inactivecaptiontext */
EIF_TYPED_VALUE F1366_14348 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_3dhilight */
EIF_TYPED_VALUE F1366_14349 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_3dhighlight */
EIF_TYPED_VALUE F1366_14350 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_btnhilight */
EIF_TYPED_VALUE F1366_14351 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_btnhighlight */
EIF_TYPED_VALUE F1366_14352 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_3ddkshadow */
EIF_TYPED_VALUE F1366_14353 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 21L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_3dlight */
EIF_TYPED_VALUE F1366_14354 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 22L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_infotext */
EIF_TYPED_VALUE F1366_14355 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 23L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_infobk */
EIF_TYPED_VALUE F1366_14356 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 24L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_hotlight */
EIF_TYPED_VALUE F1366_14357 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_gradientactivecaption */
EIF_TYPED_VALUE F1366_14358 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 27L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_gradientinactivecaption */
EIF_TYPED_VALUE F1366_14359 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 28L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_menuhilight */
EIF_TYPED_VALUE F1366_14360 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 29L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.color_menubar */
EIF_TYPED_VALUE F1366_14361 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 30L);
	return r;
}

/* {WEL_COLOR_CONSTANTS}.valid_color_constant */
EIF_TYPED_VALUE F1366_14362 (EIF_REFERENCE Current, EIF_TYPED_VALUE arg1x)
{
	GTCX
	char *l_feature_name = "valid_color_constant";
	RTEX;
#define arg1 arg1x.it_i4
	EIF_INTEGER_32 ti4_1;
	EIF_INTEGER_32 ti4_2;
	EIF_INTEGER_32 ti4_3;
	EIF_INTEGER_32 ti4_4;
	EIF_INTEGER_32 ti4_5;
	EIF_INTEGER_32 ti4_6;
	EIF_INTEGER_32 ti4_7;
	EIF_INTEGER_32 ti4_8;
	EIF_INTEGER_32 ti4_9;
	EIF_INTEGER_32 ti4_10;
	EIF_INTEGER_32 ti4_11;
	EIF_INTEGER_32 ti4_12;
	EIF_INTEGER_32 ti4_13;
	EIF_INTEGER_32 ti4_14;
	EIF_INTEGER_32 ti4_15;
	EIF_INTEGER_32 ti4_16;
	EIF_INTEGER_32 ti4_17;
	EIF_INTEGER_32 ti4_18;
	EIF_INTEGER_32 ti4_19;
	EIF_INTEGER_32 ti4_20;
	EIF_INTEGER_32 ti4_21;
	EIF_INTEGER_32 ti4_22;
	EIF_INTEGER_32 ti4_23;
	EIF_INTEGER_32 ti4_24;
	EIF_INTEGER_32 ti4_25;
	EIF_INTEGER_32 ti4_26;
	EIF_INTEGER_32 ti4_27;
	EIF_INTEGER_32 ti4_28;
	EIF_INTEGER_32 ti4_29;
	EIF_INTEGER_32 ti4_30;
	EIF_BOOLEAN Result = ((EIF_BOOLEAN) 0);
	
	RTCDT;
	RTSN;
	RTDA;
	RTLD;
	
	if ((arg1x.type & SK_HEAD) == SK_REF) arg1x.it_i4 = * (EIF_INTEGER_32 *) arg1x.it_r;
	
	RTLI(1);
	RTLR(0,Current);
	RTLIU(1);
	RTLU (SK_BOOL, &Result);
	RTLU(SK_INT32,&arg1);
	RTLU (SK_REF, &Current);
	
	RTEAA(l_feature_name, 1365, Current, 0, 1, 20874);
	RTSA(dtype);
	RTSC;
	RTME(dtype, 0);
	RTGC;
	RTDBGEAA(1365, Current, 20874);
	RTIV(Current, RTAL);
	RTHOOK(1);
	RTDBGAL(0, 0x04000000, 1,0); /* Result */
	ti4_1 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11889, dtype))(Current)).it_i4);
	ti4_2 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11878, dtype))(Current)).it_i4);
	ti4_3 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11885, dtype))(Current)).it_i4);
	ti4_4 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11890, dtype))(Current)).it_i4);
	ti4_5 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11880, dtype))(Current)).it_i4);
	ti4_6 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11873, dtype))(Current)).it_i4);
	ti4_7 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11865, dtype))(Current)).it_i4);
	ti4_8 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11875, dtype))(Current)).it_i4);
	ti4_9 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11863, dtype))(Current)).it_i4);
	ti4_10 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11883, dtype))(Current)).it_i4);
	ti4_11 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11872, dtype))(Current)).it_i4);
	ti4_12 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11894, dtype))(Current)).it_i4);
	ti4_13 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11895, dtype))(Current)).it_i4);
	ti4_14 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11882, dtype))(Current)).it_i4);
	ti4_15 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11876, dtype))(Current)).it_i4);
	ti4_16 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11877, dtype))(Current)).it_i4);
	ti4_17 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11893, dtype))(Current)).it_i4);
	ti4_18 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11874, dtype))(Current)).it_i4);
	ti4_19 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11866, dtype))(Current)).it_i4);
	ti4_20 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11884, dtype))(Current)).it_i4);
	ti4_21 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11892, dtype))(Current)).it_i4);
	ti4_22 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11891, dtype))(Current)).it_i4);
	ti4_23 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11867, dtype))(Current)).it_i4);
	ti4_24 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11896, dtype))(Current)).it_i4);
	ti4_25 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11897, dtype))(Current)).it_i4);
	ti4_26 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11870, dtype))(Current)).it_i4);
	ti4_27 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11862, dtype))(Current)).it_i4);
	ti4_28 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11868, dtype))(Current)).it_i4);
	ti4_29 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11869, dtype))(Current)).it_i4);
	ti4_30 = (((FUNCTION_CAST(EIF_TYPED_VALUE, (EIF_REFERENCE)) RTWF(11871, dtype))(Current)).it_i4);
	Result = (EIF_BOOLEAN) (EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN) ((EIF_BOOLEAN)(arg1 == ti4_1) || (EIF_BOOLEAN)(arg1 == ti4_2)) || (EIF_BOOLEAN)(arg1 == ti4_3)) || (EIF_BOOLEAN)(arg1 == ti4_4)) || (EIF_BOOLEAN)(arg1 == ti4_5)) || (EIF_BOOLEAN)(arg1 == ti4_6)) || (EIF_BOOLEAN)(arg1 == ti4_7)) || (EIF_BOOLEAN)(arg1 == ti4_8)) || (EIF_BOOLEAN)(arg1 == ti4_9)) || (EIF_BOOLEAN)(arg1 == ti4_10)) || (EIF_BOOLEAN)(arg1 == ti4_11)) || (EIF_BOOLEAN)(arg1 == ti4_12)) || (EIF_BOOLEAN)(arg1 == ti4_13)) || (EIF_BOOLEAN)(arg1 == ti4_14)) || (EIF_BOOLEAN)(arg1 == ti4_15)) || (EIF_BOOLEAN)(arg1 == ti4_16)) || (EIF_BOOLEAN)(arg1 == ti4_17)) || (EIF_BOOLEAN)(arg1 == ti4_18)) || (EIF_BOOLEAN)(arg1 == ti4_19)) || (EIF_BOOLEAN)(arg1 == ti4_20)) || (EIF_BOOLEAN)(arg1 == ti4_21)) || (EIF_BOOLEAN)(arg1 == ti4_22)) || (EIF_BOOLEAN)(arg1 == ti4_23)) || (EIF_BOOLEAN)(arg1 == ti4_24)) || (EIF_BOOLEAN)(arg1 == ti4_25)) || (EIF_BOOLEAN)(arg1 == ti4_26)) || (EIF_BOOLEAN)(arg1 == ti4_27)) || (EIF_BOOLEAN)(arg1 == ti4_28)) || (EIF_BOOLEAN)(arg1 == ti4_29)) || (EIF_BOOLEAN)(arg1 == ti4_30));
	RTVI(Current, RTAL);
	RTRS;
	RTHOOK(2);
	RTDBGLE;
	RTMD(0);
	RTLE;
	RTLO(3);
	RTEE;
	{ EIF_TYPED_VALUE r; r.type = SK_BOOL; r.it_b = Result; return r; }
#undef arg1
}

void EIF_Minit1366 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
